"use client";

import { useEffect, useState } from "react";
import { useSignalStore } from "@/store/signalStore";
import { useMarketStore } from "@/store/marketStore";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BrainCircuit, ActivitySquare, AlertCircle } from "lucide-react";

export default function SignalsPage() {
  const { symbol } = useMarketStore();
  const { prediction, fetchPrediction, isLoading } = useSignalStore();

  useEffect(() => {
    fetchPrediction(symbol, 5);
  }, [symbol, fetchPrediction]);



  return (
    <div className="flex flex-col gap-6 max-w-5xl mx-auto">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold tracking-tight text-white">AI Signals</h1>
        <p className="text-slate-400">Real-time quantitative trading signals generated by ensemble models.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="md:col-span-2 lg:col-span-3 bg-gradient-to-br from-indigo-900/20 to-slate-900 border-indigo-500/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-xl">
              <BrainCircuit className="h-6 w-6 text-indigo-400" />
              Master Signal Output
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading && !prediction ? (
              <div className="h-24 flex items-center justify-center text-slate-400">Loading AI Pipeline...</div>
            ) : (
              <div className="flex flex-col md:flex-row items-center gap-8 justify-between">
                <div className="flex flex-col items-center md:items-start gap-1">
                  <span className="text-sm text-slate-400 font-medium">Direction</span>
                  <div className={`text-5xl font-black ${
                    prediction?.signal === 'BUY' ? 'text-emerald-400' :
                    prediction?.signal === 'SELL' ? 'text-rose-400' : 'text-slate-300'
                  }`}>
                    {prediction?.signal || 'HOLD'}
                  </div>
                </div>

                <div className="flex flex-col items-center md:items-start gap-1">
                  <span className="text-sm text-slate-400 font-medium">Confidence Score</span>
                  <div className="text-4xl font-bold text-white">
                    {prediction?.confidence 
                      ? (prediction.confidence * 100).toFixed(1) + '%' 
                      : '--'}
                  </div>
                </div>

                <div className="flex flex-col items-center md:items-start gap-1">
                  <span className="text-sm text-slate-400 font-medium">ML Probability</span>
                  <div className="text-3xl font-mono text-indigo-400">
                    {prediction?.probability ? (prediction.probability * 100).toFixed(1) + '%' : '--%'}
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Signal Components */}
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle className="text-lg">Signal Components</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {/* Components data is now managed backend-side without passing all details, providing fallback UI */}
              <div className="col-span-full py-8 text-center text-slate-500">
                <AlertCircle className="h-8 w-8 mx-auto mb-2 opacity-50" />
                Detailed components are currently hidden
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
